{% set name = "WellApplication" %}
{% set version = "0.5.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/utah-geological-survey/WellApplication/archive/{{ version }}.tar.gz
  sha256: e132cde47b541da9e2d1c3be42393d9a0d893ab26acd72887d57c4be87c79eb5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pypandoc
    - pip
  run:
    - python >=3.8
    - pandas >=0.16.0
    - numpy >=0.7.0
    - matplotlib-base >=1.1
    - xmltodict >=0.6.2
    - scipy >=0.10.0
    - pyproj >=1.9.4
    - requests >=2.11.1
    - xlrd >=0.5.4

test:
  imports:
    - wellapplication
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/inkenbrandt/WellApplication
  summary: Tools used to manipulate hydrograph data; Solinst xles to pandas dataframe; hydrograph analysis; hydrology; Gannt Charts; Piper diagrams; hydrogeology; wells; groundwater; USGS data; WQP data;
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - inkenbrandt
